services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: [ "/bin/sh", "-c" ]
    network_mode: host
    env_file: .env
    command:
      - |-
        java -jar ./ch-simple/simple/target/simple-0.8-SNAPSHOT.jar