services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    entrypoint: [ "/bin/sh", "-c" ]
    command:
      - |-
        java -jar ./ch-simple/simple/target/simple-0.8-SNAPSHOT.jar